export const DashboardType = {
  TEST: 'TEST'
};

export const ChatBotType = {
  INCHAT: 'INCHAT',
  OUTCHAT: 'OUTCHAT',
  SETLANG: 'SETLANG'
};

export const LoginType = {
  AUTHENTICATE: 'AUTHENTICATE',
  GET_MENU_MASTERS_DATA: 'GET_MENU_MASTERS_DATA',
  GET_MENU_MAPPING_INFO_DATA: 'GET_MENU_MAPPING_INFO_DATA',
  GET_USERS_DATA: 'GET_USERS_DATA'
};

export const ErrorType = {
  ERROR_LOG: 'ERROR_LOG'
};

export const EmployeeType = {
  UPDATE_EMPLOYEE_DATA: 'UPDATE_EMPLOYEE_DATA',
  SET_NEW_EMPLOYEE: 'SET_NEW_EMPLOYEE',
  CREATE_NEW_EMPLOYEE: 'CREATE_NEW_EMPLOYEE',
  MODIFY_HIRE_DATE: 'MODIFY_HIRE_DATE',
  GET_CURRENT_EMPLOYEE: 'GET_CURRENT_EMPLOYEE',
  UPDATE_COMPANY_DATA: 'UPDATE_COMPANY_DATA',
  UPDATE_EVENT_REASON_DATA: 'UPDATE_EVENT_REASON_DATA',
  MODIFY_DOB: 'MODIFY_DOB',
  UPDATE_COUNTRY_OF_BIRTH: 'UPDATE_COUNTRY_OF_BIRTH',
  MODIFY_DATEOFDEATH: 'MODIFY_DATEOFDEATH',
  MODIFY_CERTIFICATE_START_DATE: 'MODIFY_CERTIFICATE_START_DATE',
  MODIFY_CERTIFICATE_END_DATE: 'MODIFY_CERTIFICATE_END_DATE',
  SET_CURRENT_EMPLOYEE: 'SET_CURRENT_EMPLOYEE',
  GET_LAST_EMPLOYEE_ID: 'GET_LAST_EMPLOYEE_ID',
  ADD_NATIONALID_DATA: 'ADD_NATIONALID_DATA',
  LIST_MYEMPLOYEES: 'LIST_MYEMPLOYEES',
  SEARCH_EMPLOYEE_ID: 'SEARCH_EMPLOYEE_ID',
  ADD_EMAILID_DATA: 'ADD_EMAILID_DATA',
  ADD_PHONE_INFO_DATA: 'ADD_PHONE_INFO_DATA',
  ADD_WORKPERMIT_INFO_DATA: 'ADD_WORKPERMIT_INFO_DATA',
  ADD_ADDRESS_INFO_DATA: 'ADD_ADDRESS_INFO_DATA',
  MODIFY_EVENT_REASON: 'MODIFY_EVENT_REASON',
  ADD_FIELDS_FOR_ARRAY: 'ADD_FIELDS_FOR_ARRAY',
  GET_BENEFITS_DATA: 'GET_BENEFITS_DATA',
  EMPTY_NEW_EMPLOYEE: 'EMPTY_NEW_EMPLOYEE',
  TEMP_LIST_MYEMPLOYEES: 'TEMP_LIST_MYEMPLOYEES',
  UPDATE_NEW_EMPLOYEE: 'UPDATE_NEW_EMPLOYEE',
  GET_LAST_TEMP_EMPLOYEE_ID: 'GET_LAST_TEMP_EMPLOYEE_ID',
  GET_ALL_EMPLOYEE: 'GET_ALL_EMPLOYEE',
  GET_CURRENT_WORKER: 'GET_CURRENT_WORKER',
  CLAIM_APPROVE: 'CLAIM_APPROVE',
  CLAIM_REJECT: 'CLAIM_REJECT',
  SKILLS_APPROVE: 'SKILLS_APPROVE',
  SKILLS_SAVE_DATA: 'SKILLS_SAVE_DATA',
  ENROLLMENT_APPROVE: 'ENROLLMENT_APPROVE',
  UPDATE_NEW_EMPLOYEE_COMPENSATION: 'UPDATE_NEW_EMPLOYEE_COMPENSATION'
};

export const AddNewSkillsType = {
  UPDATE_SKILLS_DATA: 'UPDATE_SKILLS_DATA'
};
// export const TalentPoolType = {
//   SKILLS_APPROVE: 'SKILLS_APPROVE'
// };
export const ClaimsManagementType = {
  // CLAIM_APPROVE: 'CLAIM_APPROVE'
};
export const AddNewPositionType = {
  UPDATE_POSITION_DATA: 'UPDATE_POSITION_DATA',
  POSITION_SAVE_DATA: 'POSITION_SAVE_DATA',
  CHECKED_POTENTIAL: 'CHECKED_POTENTIAL'
};

export const TalentManagementType = {
  GET_FILTERED_WORKERS: 'GET_FILTERED_WORKERS',
  GET_UNCHECKED_FILTERED_WORKERS: 'GET_UNCHECKED_FILTERED_WORKERS',
  GET_MENU_SUBMENU: 'GET_MENU_SUBMENU',
  GET_ALL_EMPLOYEE: 'GET_ALL_EMPLOYEE'
};
// Initialinzin the master types and export types, can be used for entire application level
export const MasterType = {
  // GET_MASTER_DATA: 'GET_MASTER_DATA',
  GET_MASTER_DATA_INFO: 'GET_MASTER_DATA_INFO',
  GET_ERROR_CODES_MASTER_DATA: 'GET_ERROR_CODES_MASTER_DATA',
  UPDATE_MASTER_DATA_LOCALLY: 'UPDATE_MASTER_DATA_LOCALLY',
  CREATE_MASTER_DATA_TYPE: 'CREATE_MASTER_DATA_TYPE',
  GET_RETIRAL_BENIFITS: 'GET_RETIRAL_BENIFITS',
  GET_TAX_BENIFITS: 'GET_TAX_BENIFITS',
  GET_SWIZZ_DEDUCTIONS: 'GET_SWIZZ_DEDUCTIONS',
  GET_SWISS_CANTONS: 'GET_SWISS_CANTONS'
};

export const AddressType = {
  UPDATE_ADDRESS_DATA: 'UPDATE_ADDRESS_DATA',
  TOTAL_ADDRESS_IN_GRID_ONLOAD: 'TOTAL_ADDRESS_IN_GRID_ONLOAD',
  ADDRESS_IN_GRID_EDITED: 'ADDRESS_IN_GRID_EDITED',
  ADDED_NEW_ADDRESS: 'ADDED_NEW_ADDRESS'
};

export const CurrentEmployeeType = {
  // UPDATE_JOB_INFO_DATA: 'UPDATE_JOB_INFO_DATA',
  UPDATE_COMPENSATION_DATA: 'UPDATE_PAYTYPE_DATA',
  UPDATE_PERSONAL_INFO_DATA: 'UPDATE_PERSONAL_INFO_DATA',
  UPDATE_JOB_INFO: 'UPDATE_JOB_INFO',
  UPDATE_TIME_OFF: 'UPDATE_TIME_OFF',
  APPROVE_REJECT_TIME_OFF: 'APPROVE_REJECT_TIME_OFF',
  UPDATE_TIME_OFF_COMMENTS: 'UPDATE_TIME_OFF_COMMENTS',
  // Benefits Data
  UPDATE_BENEFITS_DATA: 'UPDATE_BENEFITS_DATA',
  CANCEL_CURRENT_BENEFITS_ALLOWANCE: 'CANCEL_CURRENT_BENEFITS_ALLOWANCE',
  APPROVE_BENEFITS_ENROLLMENT: 'APPROVE_BENEFITS_ENROLLMENT',
  UPLOAD_CLAIMS_DOCUMENT: 'UPLOAD_CLAIMS_DOCUMENT',
  ADD_CLAIM: 'ADD_CLAIM'
};

export const SalaryPlanType = {
  GET_SALARYPLAN: 'GET_SALARYPLAN',
  UPDATE_MERIT: 'UPDATE_MERIT',
  UPDATE_LUMPSUM: 'UPDATE_LUMPSUM',
  UPDATE_PROMOTION: 'UPDATE_PROMOTION',
  UPDATE_ADJUSTMENT: 'UPDATE_ADJUSTMENT',
  SET_STI: 'SET_STI',
  SET_EMPLOYEES: 'SET_EMPLOYEES',
  SET_MERIT_GUIDELINES: 'SET_MERIT_GUIDELINES',
  SET_EMPLOYEE_BANDS: 'SET_EMPLOYEE_BANDS',
  SET_TARGETS: 'SET_TARGETS',
  SET_COMPENSATION_PLANNING: 'SET_COMPENSATION_PLANNING',
  ADD_SALARYPLAN_TARGET: 'ADD_SALARYPLAN_TARGET',
  DELETE_STI: 'DELETE_STI',
  ADD_STI: 'ADD_STI',
  DELETE_TARGET: 'DELETE_TARGET',
  GET_COMPENSATION_PLANNING_STATUS: 'GET_COMPENSATION_PLANNING_STATUS',
  GET_EMPLOYEES_BY_BAND: 'GET_EMPLOYEES_BY_BAND',
  SET_COMPENSATION_STATUS: 'SET_COMPENSATION_STATUS',
  SET_MERIT_AMOUNT: 'SET_MERIT_AMOUNT'
};

export const OrgChart = {
  ADD_EMPLOYEE: 'ADD_EMPLOYEE',
  CALCULATE_BUDGET: 'CALCULATE_BUDGET',
  SET_FORMATTED_BUDGET: 'SET_FORMATTED_BUDGET',
  UPDATE_EMPLOYEE: 'UPDATE_EMPLOYEE',
  DELETE_EMPLOYEE: 'DELETE_EMPLOYEE',
  CHANGE_HIERARCHY: 'CHANGE_HIERARCHY',
  CHANGE_DATA_REPRESENTATION: 'CHANGE_DATA_REPRESENTATION',
  ADD_NEW_EMPLOYEE: 'ADD_NEW_EMPLOYEE',
  SET_RATINGS: 'SET_RATINGS',
  SAVE_SIMULATED_VERSION: 'SAVE_SIMULATED_VERSION',
  LOAD_SIMULATED_VERSION: 'LOAD_SIMULATED_VERSION',
  LOAD_SPECIFIC_VERSION: 'LOAD_SPECIFIC_VERSION',
  SET_MERIT_GUIDELINES: 'SET_MERIT_GUIDELINES',
  SET_DATAGRID_EXPAND: 'SET_DATAGRID_EXPAND',
  DELETE_SIMULATED_VERSION: 'DELETE_SIMULATED_VERSION'
};

// export const MasterDataType = {
// };

export const AuditType = {
  INSERT_INTO_AUDIT: 'INSERT_INTO_AUDIT',
  UPDATE_AUDIT_DATA: 'UPDATE_AUDIT_DATA',
  AUDIT_UPDATE_FOR_COMPENSATION: 'AUDIT_UPDATE_FOR_COMPENSATION',
  INSERT_INTO_AUDIT_FOR_PERSONAL_INFO: 'INSERT_INTO_AUDIT_FOR_PERSONAL_INFO',
  UPDATE_WORKER_AUDIT_DATA: 'UPDATE_WORKER_AUDIT_DATA',
  INSERT_AUDIT_FOR_BENEFITS: 'INSERT_AUDIT_FOR_BENEFITS',
  INSERT_INTO_LEAVES_AUDIT: 'INSERT_INTO_LEAVES_AUDIT',
  UPDATE_LEAVES_AUDIT: 'UPDATE_LEAVES_AUDIT',
  UPDATE_PUBLIC_HOLIDAYS_AUDIT: 'UPDATE_PUBLIC_HOLIDAYS_AUDIT',
  UPDATE_PERFORMANCE_MANAGEMENT_AUDIT: 'UPDATE_PERFORMANCE_MANAGEMENT_AUDIT'
};

export const CompanyInfo = {
  FETCH_COMPANY_DATA: 'FETCH_COMPANY_DATA',
  UPDATE_ADDRESS_INFO: 'UPDATE_ADDRESS_INFO',
  FETCH_COMPANY_AUDIT: 'FETCH_COMPANY_AUDIT'
};

export const LeaveMasterType = {
  SET_LEAVES_MASTER_DATA: 'SET_LEAVES_MASTER_DATA',
  GET_LEAVES_MASTER_DATA: 'GET_LEAVES_MASTER_DATA',
  SET_PROCESSED_STATUS: 'SET_PROCESSED_STATUS',
  SET_LEAVES_INDIVIDUAL: 'SET_LEAVES_INDIVIDUAL',
  GET_LEAVES_INDIVIDUAL: 'GET_LEAVES_INDIVIDUAL',
  GET_LEAVES_BY_SEL_MONTH: 'GET_LEAVES_BY_SEL_MONTH'
};

export const RoleType = {
  GET_ROLES: 'GET_ROLES'
};

export const RolesApprovalType = {
  GET_ROLES_APPROVAL: 'GET_ROLES_APPROVAL',
  UPDATE_ROLES_APPROVAL_DATA: 'UPDATE_ROLES_APPROVAL_DATA'
};

export const PerformanceManagementType = {
  GET_PERFORMANCE_MANAGEMENT_DATA: 'GET_PERFORMANCE_MANAGEMENT_DATA',
  UPDATE_PERFORMANCE_MANAGEMENT_DATA: 'UPDATE_PERFORMANCE_MANAGEMENT_DATA'
};

export const ResumeBuilder = {
  FETCH_RESUME_BUILDER_DATA_AND_AUDIT: 'FETCH_RESUME_BUILDER_DATA',
  UPDATE_RESUME_BUILDER_AND_AUDIT_DATA: 'UPDATE_RESUME_BUILDER_AND_AUDIT_DATA'
};

export const CantonTaxes = {
  FETCH_FROM_DB: 'FETCH_FROM_DB',
  UPDATE_CONTON_TAXES: 'UPDATE_CONTON_TAXES',
  FETCH_FOR_ALL: 'FETCH_FOR_ALL',
  CHECK_FOR_INITIALUPLOAD: 'CHECK_FOR_INITIALUPLOAD'
};
export const PublicHolidaysType = {
  GET_PUBLIC_HOLIDAYS_DATA: 'GET_PUBLIC_HOLIDAYS_DATA',
  UPDATE_PUBLIC_HOLIDAYS_DATA: 'UPDATE_PUBLIC_HOLIDAYS_DATA'
};

export const PayRoll = {
  GET_MASTER_RETIRALS: 'GET_MASTER_RETIRALS',
  POST_MASTER_RETIRALS: 'POST_MASTER_RETIRALS',
  UPDATE_MASTER_RETIRALS: 'UPDATE_MASTER_RETIRALS',
  DELETE_MASTER_RETIRALS: 'DELETE_MASTER_RETIRALS',
  GET_MASTER_TAX_BENIFIT: 'GET_MASTER_TAX_BENIFIT',
  POST_MASTER_TAX_BENIFIT: 'POST_MASTER_TAX_BENIFIT',
  UPDATE_MASTER_TAX_BENIFIT: 'UPDATE_MASTER_TAX_BENIFIT',
  DELETE_MASTER_TAX_BENIFIT: 'DELETE_MASTER_TAX_BENIFIT',
  GET_SWISS_EMPLOYEES: 'GET_SWISS_EMPLOYEES',
  EMPTY_SWISS_EMPLOYEES: 'EMPTY_SWISS_EMPLOYEES',
  PAYROLL_POST_SUCCESS: 'PAYROLL_POST_SUCCESS',
  RESET_PAYROLL_POST_STATUS: 'RESET_PAYROLL_POST_STATUS',
  GET_EMP_PAYROLL: 'GET_EMP_PAYROLL',
  REMOVE_EMP_FROM_LIST: 'REMOVE_EMP_FROM_LIST',
  GET_SWISS_EMP_PAYSLIP: 'GET_SWISS_EMP_PAYSLIP',
  GET_EMP_PAYROLL_DETAIL: 'GET_EMP_PAYROLL_DETAIL'
};

export const houseRent = {
  GET_HOUSE_RENT: 'GET_HOUSE_RENT',
  UPLOAD_HOUSE_RECIEPTS: 'UPLOAD_HOUSE_RECIEPTS',
  RESET_HOUSE_UPLOAD_DOCS: 'RESET_HOUSE_UPLOAD_DOCS',
  ADD_NEW_RENT: 'ADD_NEW_RENT',
  UPDATE_RENT_PROPERTY: 'UPDATE_RENT_PROPERTY',
  DELETE_HOUSE_RENT: 'DELETE_HOUSE_RENT',
  FILE_DELETE_SUCCESS: 'FILE_DELETE_SUCCESS',
  HOUSE_RENT_ERROR: 'HOUSE_RENT_ERROR'
};

export const ProdSupport = {
  ADD_PROD_SUPPORT: 'ADD_PROD_SUPPORT',
  GET_PROD_SUPPORT: 'GET_PROD_SUPPORT'
};

export const Registration = {
  ADD_REGISTRATION: 'ADD_REGISTRATION',
  ADD_USER: 'ADD_USER',
  GET_LOGIN_DETAILS: 'GET_LOGIN_DETAILS'
};

export const otherBills = {
  GET_BILLS: 'GET_BILLS',
  UPLOAD_BILL_SUCCESS: 'UPLOAD_BILL_SUCCESS',
  RESET_BILL_UPLOADED: 'RESET_BILL_UPLOADED',
  ADD_NEW_BILL: 'ADD_NEW_BILL',
  UPDATE_BILL_PROPERTY: 'UPDATE_BILL_PROPERTY',
  DELETE_HOUSE_RENT: 'DELETE_HOUSE_RENT',
  DELETE_BILL: 'DELETE_BILL',
  GET_NOMINEES: 'GET_NOMINEES',
  ADD_NOMINEE: 'ADD_NOMINEE',
  DELETE_NOMINEE: 'DELETE_NOMINEE'
};

export const HRQueries = {
  ADD_HR_QUERIES: 'ADD_HR_QUERIES',
  GET_HR_QUERIES: 'GET_HR_QUERIES'
};

export const EmployeeBasedNominees = {
  FETCH_FROM_DB: 'FETCH_HEALTH_FROM_DB',
  UPDATE_NOMINEES: 'UPDATE_HEALTH_NOMINEES',
  DELETE_NOMINEE: 'DELETE_HEALTH_NOMINEE'
};

export const AdminHealthInsurance = {
  ADD_ENTRY: 'ADD_ENTRY',
  FETCH_FROM_DB_FOR_ADMIN_HEALTH_INSURANCE_BENEFITS: 'FETCH_FROM_DB_FOR_ADMIN_HEALTH_INSURANCE_BENEFITS',
  DELETE_ENTRY: 'DELETE_ENTRY'
};

export const AdminHealthInsurancePlans = {
  ADD_ENTRY_PLAN: 'ADD_ENTRY_PLAN',
  FETCH_FROM_DB_FOR_ADMIN_HEALTH_INSURANCE_BENEFITS_PLAN: 'FETCH_FROM_DB_FOR_ADMIN_HEALTH_INSURANCE_BENEFITS_PLAN',
  DELETE_ENTRY_PLAN: 'DELETE_ENTRY_PLAN'
};

export const ModuleDesigner = {
  ADD_COMPONENT: 'ADD_COMPONENT',
  LAYOUT_CHANGE: 'LAYOUT_CHANGE',
  SELECT_CONTROL: 'SELECT_CONTROL',
  CHANGE_PROPERTIES: 'CHANGE_PROPERTIES',
  SET_HOVER_CONTROL: 'SET_HOVER_CONTROL',
  ON_CHANGE_PLURAL: 'ON_CHANGE_PLURAL',
  ON_CHANGE_MODEL_NAME: 'ON_CHANGE_MODEL_NAME',
  SAVE_MODEL: 'SAVE_MODEL',
  SET_API_LIST: 'SET_API_LIST'
};
